# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
provision:
  jaeger: true
  rabbitmq: true
  mssql: true

jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true # for dev/test purposes!
    ingress:
      enabled: false
  storage:
    type: none
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

rabbitmq:
  persistence:
    enabled: false

mssql-linux:
  saPassword: "HelmMaestro123"
  persistence:
    enabled: false

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: shipy.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              nameSuffix: webapp 
              port:
                number: 7000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

webapp:
  replicaCount: 1
  image:
    repository: k8smaestro/shipy-webapp
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.2"

  container:
    name: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    enabled: true
    path: "/health"
    port: "http"
  readinessProbe:
    enabled: true
    path: "/health"
    port: "http"

  environment:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
      value: "shipy-jaeger-agent.shipy.svc.cluster.local"
    - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
      value: "6831"
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: "http://shipy-jaeger-collector.shipy.svc.cluster.local:14268"
    - name: APIServiceLocations__CustomerManagementAPI
      value: "customermanagementapi.shipy.svc.cluster.local:5100"
    - name: APIServiceLocations__ShipManagementAPI
      value: "shipmanagementapi.shipy.svc.cluster.local:5000"
    - name: APIServiceLocations__WorkshopManagementAPI
      value: "workshopmanagementapi.shipy.svc.cluster.local:5200" 

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 7000

  resources:
    requests:
      memory: 64Mi
      cpu: 64m
    limits:
      memory: 128Mi
      cpu: 256m
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
