apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: shipy
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 7000
    targetPort: 7000
  selector:
    app: webapp
    version: "1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
    version: "1.0"
  name: webapp-v1
  namespace: shipy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: "1.0"
  template:
    metadata:
      labels:
        app: webapp
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
          value: "jaeger-agent.observability.svc.cluster.local"
        - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
          value: "6831"
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.observability.svc.cluster.local:14268"
        - name: APIServiceLocations__CustomerManagementAPI
          value: "customermanagementapi.shipy.svc.cluster.local:5100"
        - name: APIServiceLocations__ShipManagementAPI
          value: "shipmanagementapi.shipy.svc.cluster.local:5000"
        - name: APIServiceLocations__WorkshopManagementAPI
          value: "workshopmanagementapi.shipy.svc.cluster.local:5200"
        image: k8smaestro/shipy-webapp:1.1
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 7000
          name: "http"
        resources:
          requests:
            memory: 64Mi
            cpu: 64m
          limits:
            memory: 128Mi
            cpu: 256m
      restartPolicy: Always
