apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipy.name" . }}-customerapi
  labels:
    {{- include "shipy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.customerapi.replicaCount }}
  selector:
    matchLabels:
      {{- include "shipy.customerapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.customerapi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shipy.customerapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.customerapi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.customerapi.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.customerapi.container.name | default .Chart.Name | cat "ctr-customerapi-" | nospace }}
          securityContext:
            {{- toYaml .Values.customerapi.securityContext | nindent 12 }}
          image: "{{ .Values.customerapi.image.repository }}:{{ .Values.customerapi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.customerapi.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.common.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}
            {{- range $key, $value := .Values.customerapi.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}   
          ports:
            - name: http
              containerPort: 5100
              protocol: TCP
          {{- if .Values.customerapi.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              {{- with .Values.customerapi.livenessProbe }}
              path: {{ .path }}
              port: {{ .port }}
              {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          {{- if .Values.customerapi.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              {{- with .Values.customerapi.readinessProbe }}
              path: {{ .path }}
              port: {{ .port }}
              {{- end }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.customerapi.resources | nindent 12 }}
      {{- with .Values.customerapi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.customerapi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.customerapi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}