apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipy.name" . }}-eventlogservice
  labels:
    {{- include "shipy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.eventlogservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "shipy.eventlogservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.eventlogservice.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shipy.eventlogservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.eventlogservice.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.eventlogservice.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.eventlogservice.container.name | default .Chart.Name | cat "ctr-eventlogservice-" | nospace }}
          securityContext:
            {{- toYaml .Values.eventlogservice.securityContext | nindent 12 }}
          image: "{{ .Values.eventlogservice.image.repository }}:{{ .Values.eventlogservice.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.eventlogservice.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.common.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}
            {{- range $key, $value := .Values.eventlogservice.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.eventlogservice.resources | nindent 12 }}
      {{- with .Values.eventlogservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventlogservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventlogservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}