apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipy.name" . }}-invoiceservice
  labels:
    {{- include "shipy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.invoiceservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "shipy.invoiceservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.invoiceservice.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shipy.invoiceservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.invoiceservice.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.invoiceservice.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.invoiceservice.container.name | default .Chart.Name | cat "ctr-invoiceservice-" | nospace }}
          securityContext:
            {{- toYaml .Values.invoiceservice.securityContext | nindent 12 }}
          image: "{{ .Values.invoiceservice.image.repository }}:{{ .Values.invoiceservice.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.invoiceservice.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.common.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}
            {{- range $key, $value := .Values.invoiceservice.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}   
          resources:
            {{- toYaml .Values.invoiceservice.resources | nindent 12 }}
      {{- with .Values.invoiceservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.invoiceservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.invoiceservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}