apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipy.name" . }}-shipapi
  labels:
    {{- include "shipy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.shipapi.service.type }}
  ports:
    - port: {{ .Values.shipapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shipy.shipapi.selectorLabels" . | nindent 4 }}