apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipy.name" . }}-workshopeventhandler
  labels:
    {{- include "shipy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workshopeventhandler.replicaCount }}
  selector:
    matchLabels:
      {{- include "shipy.workshopeventhandler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.workshopeventhandler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shipy.workshopeventhandler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.workshopeventhandler.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.workshopeventhandler.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.workshopeventhandler.container.name | default .Chart.Name | cat "ctr-workshopeventhandler-" | nospace }}
          securityContext:
            {{- toYaml .Values.workshopeventhandler.securityContext | nindent 12 }}
          image: "{{ .Values.workshopeventhandler.image.repository }}:{{ .Values.workshopeventhandler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workshopeventhandler.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.common.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}
            {{- range $key, $value := .Values.workshopeventhandler.environment }}
            - name: {{ .name | quote }}
              value: {{ include "render-value" ( dict "value" .value "context" $) | quote }}
            {{- end }}   
          resources:
            {{- toYaml .Values.workshopeventhandler.resources | nindent 12 }}
      {{- with .Values.workshopeventhandler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workshopeventhandler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workshopeventhandler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}